COLUMNS_NAME = ["estado_civil",
                "grado_instruccion",
                "sexo",
                "cono_agrup_nuevo",
                "distrito",
                "nse_ubigeo",
                "ubigeo",
                "linea_tcmax",
                "saldo_pp_sbs",
                "num_tc_sbs_6",
                "saldo_tc_sbs_6",
                "linea_tcmax_12",
                "saldo_tc_sbs_12",
                "linea_tcmax_24",
                "ingreso_prom",
                "benef_ambulatorio",
                "cie10_cap_cap21_servicios_salud",
                "flag_cuidate",
                "flag_maternidad",
                "flag_mesvig_ocur_1",
                "flag_mesvig_ocur_2",
                "flag_mesvig_ocur_3",
                "grupo_benef_ambulatorio",
                "mesvig_ocur_0",
                "mesvig_ocur_1",
                "mesvig_ocur_2",
                "mesvig_ocur_7",
                "mesvig_ocur_8",
                "monto_usd_beneficio_sin_igv",
                "monto_usd_beneficio",
                "monto_usd_coaseguro",
                "monto_usd_deducible",
                "monto_usd_saldo_acargo_afiliado",
                "monto_usd_total_gastos_presentados",
                "mto_bsigv_benef_ambulatorio",
                "mto_bsigv_cie10_cap_cap18_sintomas_anormales",
                "mto_bsigv_cie10_cap_cap19_traumatismos_envenenam",
                "mto_bsigv_cie10_cap_otros",
                "mto_bsigv_especilidad_ad_traumatologia",
                "mto_bsigv_flag_cond_riesgo_covid",
                "mto_bsigv_flag_cuidate",
                "mto_bsigv_flag_enf_recurrentes",
                "mto_bsigv_flag_maternidad",
                "mto_bsigv_flag_prevencion",
                "mto_bsigv_grupo_benef_ambulatorio",
                "mto_bsigv_grupo_benef_extra_hospitalaria",
                "mto_bsigv_grupo_benef_hospitalaria",
                "mto_bsigv_grupo_benef_otros",
                "mto_bsigv_mesvig_ocur_0",
                "mto_bsigv_mesvig_ocur_1",
                "mto_bsigv_mesvig_ocur_2",
                "mto_bsigv_mesvig_ocur_4",
                "mto_bsigv_mesvig_ocur_5",
                "mto_bsigv_mesvig_ocur_8",
                "mto_bsigv_prov_otros",
                "mto_bsigv_riesgo_leve",
                "mto_bsigv_riesgo_severo",
                "mto_bsigv_siniestro_diasem_0",
                "mto_bsigv_siniestro_diasem_1",
                "mto_bsigv_siniestro_diasem_2",
                "mto_bsigv_siniestro_diasem_3",
                "mto_bsigv_siniestro_diasem_4",
                "mto_bsigv_siniestro_diasem_5",
                "mto_bsigv_siniestro_mesyear_1",
                "mto_bsigv_siniestro_mesyear_2",
                "mto_bsigv_siniestro_mesyear_3",
                "mto_bsigv_siniestro_mesyear_4",
                "mto_bsigv_siniestro_mesyear_5",
                "mto_bsigv_siniestro_mesyear_6",
                "mto_bsigv_siniestro_mesyear_8",
                "mto_bsigv_siniestro_mesyear_9",
                "mto_bsigv_siniestro_mesyear_10",
                "mto_bsigv_tipo_proveedor_clinicas_hosp_consultorio",
                "mto_bsigv_tipo_proveedor_farmacias",
                "mto_bsigv_tipo_proveedor_operador_extranjero",
                "mto_bsigv_tipo_proveedor_otros",
                "tipo_proveedor_clinicas_hosp_consultorio"]

COLUMNS_DTYPES = {"estado_civil": "object",
                  "grado_instruccion": "object",
                  "sexo": "object",
                  "cono_agrup_nuevo": "object",
                  "distrito": "object",
                  "nse_ubigeo": "object",
                  "ubigeo": "object",
                  "linea_tcmax": "float",
                  "saldo_pp_sbs": "float",
                  "num_tc_sbs_6": "float",
                  "saldo_tc_sbs_6": "float",
                  "linea_tcmax_12": "float",
                  "saldo_tc_sbs_12": "float",
                  "linea_tcmax_24": "float",
                  "ingreso_prom": "float",
                  "benef_ambulatorio": "float",
                  "cie10_cap_cap21_servicios_salud": "float",
                  "flag_cuidate": "float",
                  "flag_maternidad": "float",
                  "flag_mesvig_ocur_1": "float",
                  "flag_mesvig_ocur_2": "float",
                  "flag_mesvig_ocur_3": "float",
                  "grupo_benef_ambulatorio": "float",
                  "mesvig_ocur_0": "float",
                  "mesvig_ocur_1": "float",
                  "mesvig_ocur_2": "float",
                  "mesvig_ocur_7": "float",
                  "mesvig_ocur_8": "float",
                  "monto_usd_beneficio_sin_igv": "float",
                  "monto_usd_beneficio": "float",
                  "monto_usd_coaseguro": "float",
                  "monto_usd_deducible": "float",
                  "monto_usd_saldo_acargo_afiliado": "float",
                  "monto_usd_total_gastos_presentados": "float",
                  "mto_bsigv_benef_ambulatorio": "float",
                  "mto_bsigv_cie10_cap_cap18_sintomas_anormales": "float",
                  "mto_bsigv_cie10_cap_cap19_traumatismos_envenenam": "float",
                  "mto_bsigv_cie10_cap_otros": "float",
                  "mto_bsigv_especilidad_ad_traumatologia": "float",
                  "mto_bsigv_flag_cond_riesgo_covid": "float",
                  "mto_bsigv_flag_cuidate": "float",
                  "mto_bsigv_flag_enf_recurrentes": "float",
                  "mto_bsigv_flag_maternidad": "float",
                  "mto_bsigv_flag_prevencion": "float",
                  "mto_bsigv_grupo_benef_ambulatorio": "float",
                  "mto_bsigv_grupo_benef_extra_hospitalaria": "float",
                  "mto_bsigv_grupo_benef_hospitalaria": "float",
                  "mto_bsigv_grupo_benef_otros": "float",
                  "mto_bsigv_mesvig_ocur_0": "float",
                  "mto_bsigv_mesvig_ocur_1": "float",
                  "mto_bsigv_mesvig_ocur_2": "float",
                  "mto_bsigv_mesvig_ocur_4": "float",
                  "mto_bsigv_mesvig_ocur_5": "float",
                  "mto_bsigv_mesvig_ocur_8": "float",
                  "mto_bsigv_prov_otros": "float",
                  "mto_bsigv_riesgo_leve": "float",
                  "mto_bsigv_riesgo_severo": "float",
                  "mto_bsigv_siniestro_diasem_0": "float",
                  "mto_bsigv_siniestro_diasem_1": "float",
                  "mto_bsigv_siniestro_diasem_2": "float",
                  "mto_bsigv_siniestro_diasem_3": "float",
                  "mto_bsigv_siniestro_diasem_4": "float",
                  "mto_bsigv_siniestro_diasem_5": "float",
                  "mto_bsigv_siniestro_mesyear_1": "float",
                  "mto_bsigv_siniestro_mesyear_2": "float",
                  "mto_bsigv_siniestro_mesyear_3": "float",
                  "mto_bsigv_siniestro_mesyear_4": "float",
                  "mto_bsigv_siniestro_mesyear_5": "float",
                  "mto_bsigv_siniestro_mesyear_6": "float",
                  "mto_bsigv_siniestro_mesyear_8": "float",
                  "mto_bsigv_siniestro_mesyear_9": "float",
                  "mto_bsigv_siniestro_mesyear_10": "float",
                  "mto_bsigv_tipo_proveedor_clinicas_hosp_consultorio": "float",
                  "mto_bsigv_tipo_proveedor_farmacias": "float",
                  "mto_bsigv_tipo_proveedor_operador_extranjero": "float",
                  "mto_bsigv_tipo_proveedor_otros": "float",
                  "tipo_proveedor_clinicas_hosp_consultorio": "float"}
