__URL__ = '<GitHub URL>'
__DESCRIPTION__ = 'Scoring de Fuga y Siniestralidad de Clientes AMI'
__BUSINESS__ = 'Salud'
__MLE__ = 'rquirozr'
__MLE_EMAIL__ = 'ricardo.quiroz@rimac.com.pe'
__DS__ = 'ypilah'
__DS_EMAIL__ = 'yuri.pila@rimac.com.pe'